name: GitHub Agentic Workflows MCP Proxy Action
description:
  Mount an MCP behind an HTTP transport to isolate the MCP from the main
  container
author: GitHub Next

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  type:
    description: 'Upstream connection type (stdio or http)'
    required: true
  container:
    description: 'Container name (deprecated, use container-image)'
    required: false
  container-image:
    description: 'Container image to run'
    required: false
  command:
    description: 'Command to execute for stdio type'
    required: false
  args:
    description: 'JSON array of arguments for the command'
    required: false
  env:
    description: 'JSON object of environment variables'
    required: false
  url:
    description: 'URL for http type connection'
    required: false
  headers:
    description: 'JSON object of HTTP headers'
    required: false
  logs-dir:
    description: 'Directory for log files'
    required: false
    default: './logs'

# Define your outputs here.
outputs:
  url:
    description: 'The URL of the proxy server'
  port:
    description: 'The port number the proxy is running on'
  token:
    description: 'The API token for accessing the proxy'

runs:
  using: node24
  main: dist/index.js
